pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('sonar-scan'){
            steps{
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kleric1993_reW16-geo-app'
            }
        }
        stage("maven"){
            steps{
            sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact'){
             steps{
                sh 'curl -uadmin:AP4tbU8yG28DhL74UFcmddLM23r -T \
                target/bio*.jar \
                 "http://52.86.130.114:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
             }
        }
             
    }
}