pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }
    stages{
        stage('sonar-scan'){
            steps{
                withSonarQubeEnv('sonarQube'){
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=kleric1993_reW16-geo-app'
                }
            }
        }
        stage("maven"){
            steps{
            sh 'mvn clean validate compile install test package'
            }
        }
        stage('upload artifact1'){
             steps{
                sh 'curl -uadmin:admin1234 -T \
                target/bio*.jar \
                 "http://100.25.2.28:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
             }
        } 
    }
}